In [1]:
import torch


In [3]:
a = torch.tensor((5,6))
b = torch.tensor((5,6))

In [15]:
x = torch.rand(100)
x

tensor([0.2342, 0.5267, 0.5234, 0.2690, 0.1853, 0.2635, 0.5196, 0.2442, 0.2666,
        0.3997, 0.5118, 0.3876, 0.9325, 0.2379, 0.8290, 0.3679, 0.2591, 0.1127,
        0.0680, 0.3329, 0.8485, 0.2607, 0.6979, 0.8704, 0.2820, 0.2536, 0.6104,
        0.9969, 0.1375, 0.5527, 0.1955, 0.0937, 0.1299, 0.7683, 0.2333, 0.6865,
        0.4343, 0.0132, 0.8583, 0.0674, 0.4067, 0.0753, 0.1643, 0.1752, 0.4757,
        0.6808, 0.5476, 0.7536, 0.8721, 0.9576, 0.7020, 0.9526, 0.3342, 0.7726,
        0.8942, 0.3891, 0.5495, 0.4606, 0.4461, 0.0596, 0.6202, 0.9619, 0.6584,
        0.2241, 0.2958, 0.8649, 0.5107, 0.1605, 0.3591, 0.9339, 0.9012, 0.3910,
        0.3613, 0.6922, 0.8161, 0.3925, 0.8878, 0.3056, 0.4759, 0.0261, 0.9251,
        0.8641, 0.0320, 0.4850, 0.1390, 0.2968, 0.0015, 0.1834, 0.2878, 0.2487,
        0.2352, 0.3161, 0.8393, 0.5607, 0.2014, 0.6998, 0.2743, 0.7136, 0.9457,
        0.8299])

In [16]:
torch.mean(x.type(torch.float32))

tensor(0.4705)

In [18]:
torch.sum(x)

tensor(47.0503)

In [20]:
x.argmin(), x.argmax()

(tensor(86), tensor(27))

In [21]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Fri Nov  1 17:53:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--